main/urls.py
from flask import Blueprint
from . import views, admin_view, errors


main = Blueprint('main', __name__)

main.add_url_rule('/', 'index', views.list_post)
main.add_url_rule('/posts/', 'posts', views.list_post)
main.add_url_rule('/post/<post_id>/', 'post_detail', views.post_detail, methods=['GET', 'POST'])
main.add_url_rule('/posts/<post_id>/preview/', 'post_preview', views.post_detail, defaults={'is_preview': True})
main.add_url_rule('/users/<username>/', 'author_info', views.author_info)

main.errorhandler(404)(errors.page_not_found)
main.errorhandler(401)(errors.handle_unauthorized)
main.add_url_rule('/<path:invalid_path>', 'handle_unmatchable', errors.handle_unmatchable)


blog_admin = Blueprint('blog_admin', __name__)
blog_admin.add_url_rule('/', view_func=admin_view.AdminIdx.as_view('index'))
blog_admin.add_url_rule('/send-confirm/', 'send_confirm', admin_view.send_confirmation)
blog_admin.add_url_rule('/email-confirm/<token>/', view_func=admin_view.ConfirmEmail.as_view('confirm_email'))

blog_admin.add_url_rule('/new-report/', view_func=admin_view.Post.as_view('new_report'))
blog_admin.add_url_rule('/posts/<post_id>/', view_func=admin_view.Post.as_view('edit_post'))
blog_admin.add_url_rule('/posts/', view_func=admin_view.PostLists.as_view('posts'))
blog_admin.add_url_rule('posts/draft/', view_func=admin_view.DraftLists.as_view('drafts'))

blog_admin.add_url_rule('/posts/statistics/', view_func=admin_view.PostStatisticList.as_view('post_statistics'))
blog_admin.add_url_rule('/posts/statistics/<post_id>/', view_func=admin_view.PostStatisticDetail.as_view('post_statistics_detail'))

blog_admin.add_url_rule('/posts/comments', view_func=admin_view.Comment.as_view('comments'))
blog_admin.add_url_rule('posts/comments/approved/', view_func=admin_view.Comment.as_view('comments_approved'),
                        defaults={'disabled': False})
blog_admin.add_url_rule('/posts/comments/<pickup>/action/', view_func=admin_view.Comment.as_view('action'))
blog_admin.add_url_rule('/posts/comments/action/', view_func=admin_view.Comments.as_view('comments_clear_action'))

blog_admin.errorhandler(404)(errors.admin_page_not_found)
blog_admin.errorhandler(401)(errors.handle_unauthorized)
blog_admin.errorhandler(403)(errors.handle_forbidden)

main/models.py
from .. import db
from ..useraccounts.models import User
import markdown2 as Markdown, bleach
import datetime, hashlib, urllib

post_status = ((0,
                'post'), (1, 'draft'))


def get_clean_html_content(html_content):
    allow_tags = ['a', 'abbr', 'acronym', 'b', 'blockquote', 'code',
                        'em', 'i', 'li', 'ol', 'pre', 'strong', 'ul',
                        'h1', 'h2', 'h3', 'h4', 'h5', 'p', 'hr', 'img',
                        'table', 'thead', 'tbody', 'tr', 'th', 'td',
                        'sup', 'sub']
    allow_attrs = {'*': ['class'],
                'a': ['href', 'rel', 'name'],
                'img': ['alt', 'src', 'title'], }
    html_content = bleach.linkify(bleach.clean(html_content, tags=allow_tags, attributes=allow_attrs, strip=True))
    return html_content


class Post(db.Document):
    title = db.StringField(max_length=255, required=True, default='New blog')
    abstract = db.StringField()
    content = db.StringField(required=True)
    content_html = db.StringField(required=True)
    author = db.ReferenceField(User)
    tags = db.ListField(db.StringField(max_length=64))
    category = db.StringField(max_length=64)
    status = db.IntField(required=True, choices=post_status, default=0)
    create_time = db.DateTimeField()
    modify_time = db.DateTimeField()

    '''override save method.'''
    def save(self, allow_set_time=False, *args, **kwargs):
        if not allow_set_time:
            time = datetime.datetime.utcnow()
            if not self.create_time:
                self.create_time = time
            self.modify_time = time

        self.content_html = Markdown.markdown(self.content, extras=['code-friendly', 'fenced-code-blocks', 'tables'])
        self.content_html = get_clean_html_content(self.content_html)

        return super(Post, self).save(*args, **kwargs)

    def post_to_dict(self):
        dict_post ={}

        dict_post['title'] = self.title
        dict_post['abstract'] = self.abstract
        dict_post['content'] = self.content
        dict_post['author'] = self.author
        dict_post['tags'] = self.tags
        dict_post['category'] = self.category
        dict_post['status'] = self.status
        dict_post['create_time'] = self.create_time.strftime('%Y-%m-%d %H:%M')
        dict_post['modify_time'] = self.modify_time.strftime('%Y-%m-%d %H:%M')

        return dict_post

    def __unicode__(self):
        return self.title

    def __str__(self):
        return self.title


class Comment(db.Document):
    post_id = db.StringField()
    post_title = db.StringField()
    author = db.StringField(required=True)
    email = db.EmailField(max_length=255)
    body = db.StringField()
    body_html = db.StringField()
    create_time = db.DateTimeField()
    disabled = db.BooleanField(default=True)
    replay_to = db.ReferenceField('self')
    gavatar_id = db.StringField(default='00000000000')

    def save(self, *args, **kwargs):
        if self.body:
            body_html = Markdown.markdown(self.body, extras=['code-friendly', 'fenced-code-blocks', 'tables'])
            self.body_html = get_clean_html_content(body_html)

        if self.email:
            self.gavatar_id = hashlib.md5(self.email.lower().encode('utf-8')).hexdigest()

        if not self.create_time:
            self.create_time = datetime.datetime.now()

        return super(Comment, self).save(*args, **kwargs)

    def get_gavatar_url(self):
        gavatar_url = '//s.gravatar.com/avatar/' + self.gavatar_id
        gavatar_url = gavatar_url + '?s=40'
        return gavatar_url

    def comment_to_dict(self):
        dict_comment = {}

        dict_comment['post_id'] = self.post_id
        dict_comment['post_title'] = self.post_title
        dict_comment['author'] = self.author
        dict_comment['email'] = self.email
        dict_comment['body'] = self.body
        dict_comment['create_time'] = self.create_time.strftime('%Y-%m-%d %H:%M')
        dict_comment['disabled'] = self.disabled
        dict_comment['gavatar_id'] = self.gavatar_id
        dict_comment['replay_to'] = self.replay_to

        return dict_comment

    def __unicode__(self):
        return self.body[:64]

    meta = {
        'ordering': ['-create_time']
    }


class PostStatistics(db.Document):
    post = db.ReferenceField(Post)
    visit_count = db.IntField(default=0)
    verbose_count_base = db.IntField(default=0)


class Tracker(db.Document):
    post = db.ReferenceField(Post)
    ip = db.StringField()
    user_agent = db.StringField()
    create_time = db.DateTimeField()

    def save(self, *args, **kwargs):
        if not self.create_time:
            self.create_time = datetime.datetime.now()
        return super(Tracker, self).save(*args, **kwargs)

    def __unicode__(self):
        return self.ip

    meta = {
        'allow_inheritance': True,
        'indexes': ['ip'],
        'ordering': ['-create_time']
    }

main/forms.py
#!usr/bin/env/ python
# -*- coding: utf-8 -*-

from flask_wtf import FlaskForm
from wtforms import StringField, PasswordField, BooleanField, TextAreaField, \
    HiddenField, RadioField, FileField, SubmitField, IntegerField
from wtforms.validators import DataRequired, Length, Email, Regexp

from . import models


class PostForm(FlaskForm):
    title = StringField('Title', validators=[DataRequired()])
    category = StringField('Category')
    tags = StringField('Tags')
    abstract = TextAreaField('Abstract')
    content = TextAreaField('Content')
    status = HiddenField('status')
    post_id = HiddenField('post_id')


class CommentForm(FlaskForm):
    email = StringField('* Email', validators=[DataRequired(), Length(1, 128), Email()])
    author = StringField('* Name', validators=[DataRequired(), Length(1, 200)])
    body = TextAreaField('* Comment <small><span class="label label-info">markdown</span></small>',
                         validators=[DataRequired()])
    comment_id = HiddenField('comment_id')

main/views.py
from flask import redirect, render_template, url_for, request, g, flash, session, abort, current_app
from flask.views import MethodView
from . import models, forms
from mongoengine.queryset.visitor import Q
from ..config import BlogSettings
from flask_login import current_user
from ..main import signals

PER_PAGE = BlogSettings['paginate'].get('per_page', 10)


def index():
    return render_template('main/index.html')


def list_post():
    posts = models.Post.objects.filter(status=0).order_by('-create_time')
    tags = posts.distinct('tags')

    cur_tag = request.args.get('tag')
    cur_category = request.args.get('category')
    cur_kws = request.args.get('keywords')

    if cur_tag:
        posts = posts.filter(tags=cur_tag)

    if cur_category:
        posts = posts.filter(category=cur_category)

    if cur_kws:
        posts = posts.filter(Q(content__icontains=cur_kws) | Q(title__icontains=cur_kws) | Q(abstract__icontains=cur_kws))

    # use mongoengine's _get_collection() function to query aggregate
    cursor_for_category = models.Post._get_collection().aggregate([
        {
            '$group': {'_id': {'category': '$category'}, 'name': {'$first': '$category'}, 'count': {'$sum': 1}}
        }
        ])

    try:
        cur_page = int(request.args.get('page', 1))
    except ValueError:
        cur_page = 1

    posts = posts.paginate(page=cur_page, per_page=PER_PAGE)

    data = { }

    data['posts'] = posts
    data['tags'] = tags
    data['cur_tag'] = cur_tag
    data['cur_category'] = cur_category
    data['keywords'] = cur_kws
    data['cursor_for_category'] = cursor_for_category

    return render_template('main/index.html', **data)


def post_detail(post_id, is_preview=False):
    post = models.Post.objects.get_or_404(id=post_id)

    if post.status == 1 and current_user.is_anonymous:
        abort(404)
    data = {}
    data['allow_share_article'] = BlogSettings['allow_share_article']
    data['allow_comment'] = BlogSettings['allow_comment']
    data['post'] = post

    if request.form:
        form = forms.CommentForm(obj=request.form)
    else:
        obj = {'email': session.get('email'), 'author': session.get('author'),}
        form = forms.CommentForm(**obj)
    if form.validate_on_submit():
        '''commit comment.'''
        comment = models.Comment()
        comment.author = form.author.data.strip()
        comment.email = form.email.data.strip()
        comment.post_id = post_id
        comment.post_title = post.title
        comment.body = form.body.data.strip()
        comment.save()

        session['email'] = form.email.data.strip()
        session['author'] = form.author.data.strip()

        url = '{0}#comment'.format(url_for('main.post_detail', post_id=post_id))
        url = '{0}#comment'.format(request.full_path)
        msg = 'Succeed to comment, and it will be displayed when the administrator reviews it.'
        flash(msg, 'success')
        return redirect(url)

    if data['allow_comment']:
        data['comment_html'] = post_comment(post_id, form) if post_comment else ''

    if not is_preview:
        signals.post_visited.send(current_app._get_current_object(), post=post)

    template_name = 'main/post.html'

    return render_template(template_name, **data)


def post_comment(post_id, form=None, *args, **kwargs):
    # view method of comment form.
    template_name = 'main/comments.html'
    comments = models.Comment.objects(post_id=post_id, disabled=False).order_by('create_time')

    data = {
        'form': form,
        'comments': comments if comments else '',
        'slug': post_id,
    }

    return render_template(template_name, **data)

def author_info(username):
    author = models.User.objects.get_or_404(username=username)

    posts = models.Post.objects.filter(status=0, author=author).order_by('-create_time')
    cur_page = request.args.get('page', 1)

    posts = posts.paginate(page=int(cur_page), per_page=10)

    data={}
    data['user'] = author
    data['posts']= posts

    return render_template('main/author.html', **data)

templates/main/author.html
{% extends 'base.html' %}

{% block title %} Author | {{ user.username }} {% endblock %}
{% block header %}
<header class="masthead" style="background-image: url({{ url_for('static',filename='img/bg/home-bg.jpg') }})">
        <div class="overlay"></div>
        <div class="container">
            <div class="row">
                <div class="col-lg-8 col-lg-offset-2 col-md-10 col-md-offset-1">
                    <div class="site-heading" style="text-align:center">
                        <h1>About Author</h1>
                        <span class="subheading">Coding · Thinking · Moving </span>
                    </div>
                </div>
            </div>
        </div>
    </header>
{% endblock %}
{% block main %}
    <article>
        <div class="container">
            <div class="row">
                <div class="col-lg-8 col-lg-offset-2 col-md-10 col-md-offset-1">
                    <div class="row">
                        <h3>About {{ user.username }} </h3>
                        <hr>
                        <dl class="dl-horizontal">
                            <dt>Username:</dt>
                            <dd>{{ user.username }}</dd>
                        </dl>
                        <dl class="dl-horizontal">
                            <dt>Biography:</dt>
                            <dd>{{ user.about_me }}</dd>
                        </dl>
                        <dl class="dl-horizontal">
                            <dt>Social Network:</dt>
                            <dd>
                                {% if user.social_networks['github']['url'] %}
                                    <a href='{{ user.social_networks["github"]["url"] }}'><i class="fa fa-github fa-lg"></i></a>
                                {% endif %}
                                {% if user.social_networks['twitter']['url'] %}
                                    <a href='{{ user.social_networks["twitter"]["url"] }}'><i class="fa fa-twitter fa-lg"></i></a>
                                {% endif %}
                                {% if user.social_networks['weibo']['url'] %}
                                    <a href='{{ user.social_networks["weibo"]["url"] }}'><i class="fa fa-weibo fa-lg"></i></a>
                                {% endif %}
                                {% if user.social_networks['facebook']['url'] %}
                                    <a href='{{ user.social_networks["facebook"]["url"] }}'><i class="fa fa-facebook fa-lg"></i></a>
                                {% endif %}
                                {% if user.social_networks['wechat']['url'] %}
                                    <a id="btn_weixin" href='{{ user.social_networks["wechat"]["url"] }}'><i class="fa fa-weixin fa-lg"></i></a>
                                    <div id="weixin" class="hidden">
                                        <br>
                                        <img src="{{ user.social_networks["weixin"]["url"] }}?imageView/2/w/150" title="weixin">
                                    </div>
                                {% endif %}                
                            </dd>
                        </dl>
                        <dl class="dl-horizontal">
                            <dt>Homepage:</dt>
                            <dd>
                                {% if user.homepage_url %}
                                <a href="{{ user.homepage_url }}"><i class="fa fa-home fa-lg"></i></a> {{ user.homepage_url }}
                                {% else %}
                                Not yet
                                {% endif %}
                            </dd>
                        </dl>
                    </div>
                    
                </div>
            </div>
            
            <div class="row">
                <div class="col-lg-8 col-lg-offset-2 col-md-10 col-md-offset-1">
                    <h3>Articles</h3><hr>
                    <ul>
                        {% for post in posts.items %}
                            <li><a href="{{ url_for('main.post_detail', post_id=post.id) }}">{{ post.title }}</a></li>
                        {% else %}
                            <p class="post-subtitle">No articles found here</p>
                        {% endfor %}
                    </ul>
                    <!-- Pager -->
                    <ul class="pager">
                        {% if posts.has_next %}
                        <li class="next">
                            <a href="?page={{ posts.next_num }}">Older Posts &rarr;</a>
                        </li>
                        {% endif %}
                        {% if posts.has_prev %}
                            <li class="next"><a href="?page={{ posts.prev_num }}">Previous Posts</a></li>
                        {% endif %}
                    </ul>
                </div>
            </div>
        </div>
    </article>
{% endblock %}

{% block js %}
{% endblock %}

templates/main/comments.html
<a name="comment"></a>
<h3>Comments</h3>
<br>

{% import "_msg.html" as messages %}
{{ messages.render_msg() }}

{% import '_form.html' as forms %}
<form method="post" action="#comment">
    {{ forms.render(form) }}
    <button type="submit" class="btn btn-primary" name="post-comment" value="post-comment">Submit</button>
</form>
<br>
<table class="table">
    {% for comment in comments %}
    <tr>
        <td style="width: 8%">
            <img class="media-object" src="{{ comment.get_gavatar_url() }}" alt="user-avatar">
        </td>
        <td style="word-wrap:break-word;word-break:break-all;">
            <h4>{{ comment.author }}
            </h4>
            <div>
                {{ comment.body_html|safe }}
            </div>
        </td>
        <td style="width: 25%">
            <small>{{ comment.create_time.strftime('%Y.%m.%d %H:%M') }}</small>
        </td>
    </tr>
    {% endfor %}
</table>

templates/main/index.html
{% extends 'base.html' %}

{% block main %}
<div class="container">
      <div class="row">
        <div class="col-lg-8 col-lg-offset-1 col-md-10">
        {% for post in posts.items %}
          <div class="post-preview">
            <a href="{{ url_for('main.post_detail', post_id=post.id) }}">
              <h2 class="post-title">
                {{ post.title }}
              </h2>
            </a>
              <h3 class="post-subtitle">
                {{ post.abstract }}
              </h3>
            <p class="post-meta">Posted by <a href="#">{{ post.author.username }}</a> on {{ moment(post.create_time).format('YYYY/MM/DD, h:mm a') }}</p>
            <p class="post-meta">category: <a href="#">{{ post.category }}</a></p>
            <p class="post-meta">Tags:{% for tag in post.tags %} <a href="#">{{ tag }}</a>{% endfor %}</p>
          </div>
          {% if not loop.last %}
          <hr>
          {% endif %}
          {% else %}
            <p class="post-subtitle">
                No articles found here
            </p>
        {% endfor %}
        <hr>
            <div class="clearfix">
            {% if posts.has_prev %}
                <a class="btn btn-primary float-in-left" href="?page={{ posts.prev_num }}
                        {%- if cur_category %}&category={{ cur_category }}{% endif %}
                        {%- if keywords %}&keywords={{ keywords }}{% endif %}
                        {%- if cur_tag %}&tag={{ cur_tag }}{% endif %}"> &larr;Previous Posts</a>
            {% endif %}
            {% if posts.has_next %}
                <a class="btn btn-primary float-in-right" href="?page={{ posts.next_num }}
                        {%- if cur_category %}&category={{ cur_category }}{% endif %}
                        {%- if cur_tag %}&tag={{ cur_tag }}{% endif %}">Older Posts &rarr;</a>
            {% endif %}
            </div>
        </div>
        <div class="col-lg-3 col-md-2">
            <h3>Search</h3>
            <hr/>
            <form id="search-form">
              <div class="form-group">
                <div class="input-group">
                  <input type="text" class="form-control" id="search" name="keywords" placeholder="search" value="{% if keywords %}{{ keywords }}{% endif %}">
                <div class="input-group-addon"><i class="fa fa-search"></i></div>
                </div>
              </div>
            </form>
            <br>

            <h3>Tags</h3>
            <hr/>
            {% for tag in tags %}
                <a href="?tag={{tag}}" class="post-tag">
                    {% if tag == cur_tag %}
                    <span class="label label-primary">
                        {{ tag }}
                        <small><span class="glyphicon glyphicon-remove small rm-filter" aria-hidden="true"></span></small>
                    </span>

                    {% else %}
                    <span class="label label-default">
                        {{ tag }}
                    </span>

                    {% endif %}
                </a>
                &nbsp;
            {% endfor %}


            <h3>Category</h3>
            <hr/>
            <div class="list-group">
                {% for category in cursor_for_category %}
                    {% if category and category.name %}
                        {% if cur_category == category.name %}
                            <a href="?category={{ category.name }}" class="list-group-item category-list active">{{ category.name }}
                            <small><span class="glyphicon glyphicon-remove small rm-filter" aria-hidden="true"></span></small>
                            <span class="badge">&nbsp;{{ category.count }}&nbsp;</span></a>
                        {% else %}
                            <a href="?category={{ category.name }}" class="list-group-item category-list ">{{ category.name }}
                            <span class="badge">&nbsp;{{ category.count }}&nbsp;</span></a>
                        {% endif %}
                    {% endif %}
                {% endfor %}
            </div>
        </div>
      </div>
    </div>
{% endblock %}

{% block js %}
<script type="text/javascript">
$('.rm-filter').on('click', function (event) {
    location.href = "/";
    return false;
  });
</script>
{% endblock %}

templates/main/post.html
{% extends 'base.html' %}
{% block title %}{{ post.title }}{% endblock %}

{% block header %}
<header class="masthead" style="background-image: url({{ url_for('static',filename='img/bg/home-bg.jpg') }})">
      <div class="overlay"></div>
      <div class="container">
        <div class="row">
          <div class="col-lg-8 col-lg-offset-2 col-md-10 col-md-offset-1">
            <div class="post-heading" style="text-align:center">
              <h1>{{ post.title }}</h1><br>
                <span class="meta">Posted by <a href="{{ url_for('main.author_info', username=post.author.username) }}">{{ post.author.username }}</a> on {{ moment(post.create_time).format('YYYY/MM/DD, h:mm a') }}</span>
                {% if post.category%}
                <span class="meta">Category: <a href="{{ url_for('main.index') }}?category={{ post.category }}">{{ post.category }}</a></span>
                {% endif %}
                <span class="meta">Tags:
                    {% for tag in post.tags %} <a href="{{ url_for('main.index') }}?tag={{ tag }}">{{ tag }}</a>  {% endfor %}
                </span>
            </div>
          </div>
        </div>
      </div>
    </header>
{% endblock %}

{% block main %}
    <div class="container">
        <article>
            <div class="row">
                <div class="col-lg-8 col-lg-offset-2 col-md-10 col-md-offset-1">
                    {{ post.content_html|safe }}
                </div>
            </div>

            {% if allow_share_article %}
            <div class="row">
                <div class="col-lg-8 col-lg-offset-2 col-md-10 col-md-offset-1">
                    <hr>
                    <div class="share-component" data-sites="wechat,weibo,qq,douban,twitter,google,facebook,linkedin"><span>Share to:</span></div>
                </div>
            </div>
            {% endif %}
        </article>
        <hr>
        {% if allow_comment %}
            <article>
                <div class="row">
                    <div class="col-lg-8 col-lg-offset-2 col-md-10 col-md-offset-1">
                        {{ comment_html|safe }}
                    </div>
                </div>
                <div class="up-to-top">
                    <button id="button-up" class="glyphicon glyphicon-chevron-up"></button>
                </div>
            </article>
        {% endif %}
    </div>
{% endblock %}
{% block js %}
<script src="https://cdn.bootcss.com/social-share.js/1.0.16/js/social-share.min.js"></script>
<script>
 $('#button-up').on('click',function (event) {
     $('html,body').animate({
         scrollTop:0
     },500)
 })
$(".up-to-top").mouseover(function(){
	$("#button-up").css("background-color","#00A1D6");
    $("#button-up").css("color","#F6F9FA");
	});
 $(".up-to-top").mouseout(function(){
	$("#button-up").css("background-color","#ccc");
    $("#button-up").css("color","#00A1D6");
	});
$(window).on('scroll', function () {
    if($(window).scrollTop() > $(window).height())
        $('#button-up').fadeIn();
    else
        $('#button-up').fadeOut();
})

$(window).trigger('scroll');
</script>
<style>
#button-up {
    position: fixed;
    right: 80px;
    bottom: 30px;
    height: 30px;
    top: 500px;
    border: 0px;
    color: #00A1D6;
}
</style>
{% endblock %}