main/urls.py
from flask import Blueprint
from . import views, admin_view, errors


main = Blueprint('main', __name__)

main.add_url_rule('/', 'index', views.list_post)
main.add_url_rule('/posts/', 'posts', views.list_post)
main.add_url_rule('/post/<post_id>/', 'post_detail', views.post_detail, methods=['GET', 'POST'])
main.add_url_rule('/posts/<post_id>/preview/', 'post_preview', views.post_detail, defaults={'is_preview': True})
main.add_url_rule('/users/<username>/', 'author_info', views.author_info)

main.errorhandler(404)(errors.page_not_found)
main.errorhandler(401)(errors.handle_unauthorized)
main.add_url_rule('/<path:invalid_path>', 'handle_unmatchable', errors.handle_unmatchable)


blog_admin = Blueprint('blog_admin', __name__)
blog_admin.add_url_rule('/', view_func=admin_view.AdminIdx.as_view('index'))
blog_admin.add_url_rule('/send-confirm/', 'send_confirm', admin_view.send_confirmation)
blog_admin.add_url_rule('/email-confirm/<token>/', view_func=admin_view.ConfirmEmail.as_view('confirm_email'))

blog_admin.add_url_rule('/new-report/', view_func=admin_view.Post.as_view('new_report'))
blog_admin.add_url_rule('/posts/<post_id>/', view_func=admin_view.Post.as_view('edit_post'))
blog_admin.add_url_rule('/posts/', view_func=admin_view.PostLists.as_view('posts'))
blog_admin.add_url_rule('posts/draft/', view_func=admin_view.DraftLists.as_view('drafts'))

blog_admin.add_url_rule('/posts/statistics/', view_func=admin_view.PostStatisticList.as_view('post_statistics'))
blog_admin.add_url_rule('/posts/statistics/<post_id>/', view_func=admin_view.PostStatisticDetail.as_view('post_statistics_detail'))

blog_admin.add_url_rule('/posts/comments', view_func=admin_view.Comment.as_view('comments'))
blog_admin.add_url_rule('posts/comments/approved/', view_func=admin_view.Comment.as_view('comments_approved'),
                        defaults={'disabled': False})
blog_admin.add_url_rule('/posts/comments/<pickup>/action/', view_func=admin_view.Comment.as_view('action'))
blog_admin.add_url_rule('/posts/comments/action/', view_func=admin_view.Comments.as_view('comments_clear_action'))

blog_admin.errorhandler(404)(errors.admin_page_not_found)
blog_admin.errorhandler(401)(errors.handle_unauthorized)
blog_admin.errorhandler(403)(errors.handle_forbidden)

main/views.py
from flask import redirect, render_template, url_for, request, g, flash, session, abort, current_app
from flask.views import MethodView
from . import models, forms
from mongoengine.queryset.visitor import Q
from ..config import BlogSettings
from flask_login import current_user
from ..main import signals

PER_PAGE = BlogSettings['paginate'].get('per_page', 10)


def index():
    return render_template('main/index.html')


def list_post():
    posts = models.Post.objects.filter(status=0).order_by('-create_time')
    tags = posts.distinct('tags')

    cur_tag = request.args.get('tag')
    cur_category = request.args.get('category')
    cur_kws = request.args.get('keywords')

    if cur_tag:
        posts = posts.filter(tags=cur_tag)

    if cur_category:
        posts = posts.filter(category=cur_category)

    if cur_kws:
        posts = posts.filter(Q(content__icontains=cur_kws) | Q(title__icontains=cur_kws) | Q(abstract__icontains=cur_kws))

    # use mongoengine's _get_collection() function to query aggregate
    cursor_for_category = models.Post._get_collection().aggregate([
        {
            '$group': {'_id': {'category': '$category'}, 'name': {'$first': '$category'}, 'count': {'$sum': 1}}
        }
        ])

    try:
        cur_page = int(request.args.get('page', 1))
    except ValueError:
        cur_page = 1

    posts = posts.paginate(page=cur_page, per_page=PER_PAGE)

    data = { }

    data['posts'] = posts
    data['tags'] = tags
    data['cur_tag'] = cur_tag
    data['cur_category'] = cur_category
    data['keywords'] = cur_kws
    data['cursor_for_category'] = cursor_for_category

    return render_template('main/index.html', **data)


def post_detail(post_id, is_preview=False):
    post = models.Post.objects.get_or_404(id=post_id)

    if post.status == 1 and current_user.is_anonymous:
        abort(404)
    data = {}
    data['allow_share_article'] = BlogSettings['allow_share_article']
    data['allow_comment'] = BlogSettings['allow_comment']
    data['post'] = post

    if request.form:
        form = forms.CommentForm(obj=request.form)
    else:
        obj = {'email': session.get('email'), 'author': session.get('author'),}
        form = forms.CommentForm(**obj)
    if form.validate_on_submit():
        '''commit comment.'''
        comment = models.Comment()
        comment.author = form.author.data.strip()
        comment.email = form.email.data.strip()
        comment.post_id = post_id
        comment.post_title = post.title
        comment.body = form.body.data.strip()
        comment.save()

        session['email'] = form.email.data.strip()
        session['author'] = form.author.data.strip()

        url = '{0}#comment'.format(url_for('main.post_detail', post_id=post_id))
        url = '{0}#comment'.format(request.full_path)
        msg = 'Succeed to comment, and it will be displayed when the administrator reviews it.'
        flash(msg, 'success')
        return redirect(url)

    if data['allow_comment']:
        data['comment_html'] = post_comment(post_id, form) if post_comment else ''

    if not is_preview:
        signals.post_visited.send(current_app._get_current_object(), post=post)

    template_name = 'main/post.html'

    return render_template(template_name, **data)


def post_comment(post_id, form=None, *args, **kwargs):
    # view method of comment form.
    template_name = 'main/comments.html'
    comments = models.Comment.objects(post_id=post_id, disabled=False).order_by('create_time')

    data = {
        'form': form,
        'comments': comments if comments else '',
        'slug': post_id,
    }

    return render_template(template_name, **data)

def author_info(username):
    author = models.User.objects.get_or_404(username=username)

    posts = models.Post.objects.filter(status=0, author=author).order_by('-create_time')
    cur_page = request.args.get('page', 1)

    posts = posts.paginate(page=int(cur_page), per_page=10)

    data={}
    data['user'] = author
    data['posts']= posts

    return render_template('main/author.html', **data)

templates/_form.html
{% macro render(form) -%}

{% for field in form %}
  {% if field.type in ['CSRFTokenField', 'HiddenField'] %}
    {{ field() }}

  {% elif field.type == "BooleanField" %}
    <div class="checkbox">
    <label>
      {{ field() }} {{ field.label }}
    </label>
    </div>

  {% elif field.type == "RadioField" %}
    {{ field.label }}
    {% for subfield in field %}
      <div class="radio">
        <label>{{ subfield }} {{ subfield.label }}</label>
      </div>
    {% endfor %}

  {% else %}
    <div class="clearfix {% if field.errors %}has-error{% endif %} form-group">
      {{ field.label }}
        {% if field.type == "TextAreaField" %}
          {{ field(class_="form-control", rows=10) }}
        {% else %}
          {{ field(class_="form-control") }}
        {% endif %}

        {% if field.errors or field.help_text %}
          <span class="help-block">
          {% if field.errors %}
            {{ field.errors|join(' ') }}
          {% else %}
            {{ field.help_text }}
          {% endif %}
          </span>
        {% endif %}
    </div>
  {% endif %}
{% endfor %}

{% endmacro %}

templates/_msg.html
{% macro render_msg() %}

{% with messages = get_flashed_messages(with_categories=true) %}
  {% if messages %}
    <div class="flash_msg">
    {% for category, message in messages %}
      {% if category == 'message' %}
        {% set category='info' %}
      {% endif %}
      <div class="alert alert-{{ category }} alert-dismissible" role="alert" style="margin-bottom: 0px">
          <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
          {{ message }}
      </div>
    {% endfor %}
    </div>
  {% endif %}
{% endwith %}

{% endmacro %}

templates/_pagination.html
{% macro render_pagination(pagination) %}
  <nav>
    <ul class="pagination">
      {% if not pagination.has_prev %}
        <li class="disabled">
            <span aria-hidden="true">&laquo;</span>
        </li>
      {% else %}
        <li>
        <a href="?page={{ pagination.prev_num }}" aria-label="Previous">
          <span aria-hidden="true">&laquo;</span>
        </a>
        </li>
      {% endif %}
    
      {%- for page in pagination.iter_pages() %}
        {% if page %}
          {% if page != pagination.page %}
            <li><a href="?page={{ page }}">{{ page }}</a></li>
          {% else %}
            <li class="disabled"><a href="?page={{ page }}"><strong>{{ page }}</strong></a></li>
          {% endif %}
        {% else %}
          <!-- <span class=ellipsis>…</span> -->
          <li><a href="#">...</a></li>
        {% endif %}
      {%- endfor %}

      {% if not pagination.has_next %}
        <li class="disabled">
          <span aria-hidden="true">&raquo;</span>
        </li>
      {% else %}
        <li>
          <a href="?page={{ pagination.next_num }}" aria-label="Next">
            <span aria-hidden="true">&raquo;</span>
          </a>
        </li>
      {% endif %}      
    </ul>
  </nav>
{% endmacro %}

templates/base.html
<!DOCTYPE html>
<html lang="en">

  <head>

    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>Simple Blog</title>
    {{ moment.include_jquery() }}
    {{ moment.include_moment() }}
    <!-- Bootstrap core CSS -->
    <!--<link href={{ url_for('static',filename='css/bootstrap.min.css') }} rel="stylesheet">-->
    <link href="//cdn.bootcss.com/bootstrap/3.3.5/css/bootstrap.min.css" rel="stylesheet">
    <!-- Custom fonts for this template -->
    <!--<link href={{ url_for('static',filename='css/font-awesome.min.css') }} rel="stylesheet" type="text/css">-->
    <link href="//cdn.bootcss.com/font-awesome/4.4.0/css/font-awesome.min.css" rel="stylesheet">


    <link href={{ url_for('static',filename='css/clean-blog.min.css') }} rel="stylesheet">
    <link href="{{ url_for('static', filename='css/simpleblog.css') }}" rel="stylesheet">

    <link rel="stylesheet" href="//cdn.bootcss.com/highlight.js/9.9.0/styles/default.min.css">
    <link href="https://cdn.bootcss.com/social-share.js/1.0.16/css/share.min.css" rel="stylesheet">
    <style> html{display : none ; } </style>
    <script>
    if( self == top ) {
              document.documentElement.style.display = 'block' ;
       } else {
           top.location = self.location ;
       }
    </script>
    <!-- Custom styles for this template -->


  </head>

  <body>
    <!-- Navigation -->
    <nav class="navbar navbar-default navbar-custom navbar-fixed-top" id="mainNav">
        <div class="container-fluid">
            <div class="navbar-header page-scroll">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" href="{{ url_for('main.index') }}">Simple Blog</a>
            </div>
            <!-- Collect the nav links, forms, and other content for toggling -->
            <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                <ul class="nav navbar-nav navbar-right">
                    <li class="nav-item">
                      <a class="nav-link" href="{{ url_for('main.index') }}">Home</a>
                    </li>
                    <li class="nav-item">
                      <a class="nav-link" href="#">Sample Post</a>
                    </li>
                    <li class="nav-item">
                      <a class="nav-link" href="#">About</a>
                    </li>
                    <li class="nav-item">
                      <a class="nav-link" href="{{ url_for('useraccounts.login') }}">SignIn</a>
                    </li>
                </ul>
            </div>
        </div>
    </nav>

    <!-- Page Header -->
    {% block header %}
    <header class="masthead" style="background-image: url({{ url_for('static',filename='img/bg/home-bg.jpg') }})">
      <div class="overlay"></div>
      <div class="container">
        <div class="row">
          <div class="col-lg-8 col-lg-offset-2 col-md-10 col-md-offset-1">
            <div class="site-heading">
              <h1>Simple Blog</h1><br>
                <span class="subheading">Coding · Thinking · Moving</span>
            </div>
          </div>
        </div>
      </div>
    </header>
    {% endblock %}

    <!-- Main Content -->
    {% block main %}{% endblock %}
    <hr>

    <!-- Footer -->
    <footer>
      <div class="container">
        <div class="row">
          <div class="col-lg-8 col-lg-offset-2 col-md-10 col-md-offset-1">
            <ul class="list-inline text-center">
              <li class="list-inline-item">
                <a href="#">
                  <span class="fa-stack fa-lg">
                    <i class="fa fa-circle fa-stack-2x"></i>
                    <i class="fa fa-twitter fa-stack-1x fa-inverse"></i>
                  </span>
                </a>
              </li>
              <li class="list-inline-item">
                <a href="#">
                  <span class="fa-stack fa-lg">
                    <i class="fa fa-circle fa-stack-2x"></i>
                    <i class="fa fa-facebook fa-stack-1x fa-inverse"></i>
                  </span>
                </a>
              </li>
              <li class="list-inline-item">
                <a href="#">
                  <span class="fa-stack fa-lg">
                    <i class="fa fa-circle fa-stack-2x"></i>
                    <i class="fa fa-github fa-stack-1x fa-inverse"></i>
                  </span>
                </a>
              </li>
            </ul>
            <p class="copyright text-muted">Copyright &copy; Simple Blog 2018</p>
          </div>
        </div>
      </div>
    </footer>

    <!-- Bootstrap core JavaScript -->
    <script src={{ url_for('static',filename='js/jquery.min.js') }}></script>
    <script src={{ url_for('static',filename='js/bootstrap.bundle.min.js') }}></script>
    <script src={{ url_for('static',filename='js/bootstrap.min.js') }}></script>

    <!-- Custom scripts for this template -->
    <script src={{ url_for('static',filename='js/clean-blog.min.js') }}></script>
    <script src="https://cdn.bootcss.com/social-share.js/1.0.16/js/social-share.min.js"></script>
  {% block js %}
  {% endblock %}
  </body>

</html>

templates/login_base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">
    <title>{% block title %}Simple Blog Admin{% endblock %}</title>

    <link rel="icon" type="image/png" sizes="32x32" href="{{ url_for('static', filename='img/favicon-32x32.png') }}">
    <link rel="icon" type="image/png" sizes="96x96" href="{{ url_for('static', filename='img/favicon-96x96.png') }}">
    <link rel="icon" type="image/png" sizes="16x16" href="{{ url_for('static', filename='img/favicon-16x16.png') }}">

    <!-- Bootstrap Core CSS -->
    <link href="//cdn.bootcss.com/bootstrap/3.3.5/css/bootstrap.min.css" rel="stylesheet">
    <link href="//cdn.bootcss.com/font-awesome/4.4.0/css/font-awesome.min.css" rel="stylesheet">
    <link href="{{ url_for('static', filename='css/simpleblog.css') }}" rel="stylesheet">


    <!-- Custom CSS -->

    {% block css %}{% endblock %}
    <style> html{display : none ; } </style>
    <script>
    if( self == top ) {
              document.documentElement.style.display = 'block' ;
       } else {
           top.location = self.location ;
       }
    </script>

    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
        <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
        <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
    <![endif]-->
</head>
<body>
    <!-- Navigation -->
    <nav class="navbar navbar-default">
      <div class="container-fluid">
        <!-- Brand and toggle get grouped for better mobile display -->
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="{{ url_for('main.index') }}">Simple Blog</a>
        </div>

        <!-- Collect the nav links, forms, and other content for toggling -->
        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
          <ul class="nav navbar-nav">
            <li class="_active"><a href="{{ url_for('blog_admin.index') }}">Home <span class="sr-only">(current)</span></a></li>

            {% if g.identity.allow_write %}
            <li class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">Posts <span class="caret"></span></a>
              <ul class="dropdown-menu" role="menu">
                <li><a href="{{ url_for('blog_admin.posts') }}">All Posts</a></li>
                <li><a href="{{ url_for('blog_admin.new_report') }}">New Post</a></li>
                <li><a href="{{ url_for('blog_admin.drafts') }}">Drafts</a></li>
                <!-- <li class="divider"></li> -->

                <li class="divider"></li>
                <li><a href="#">Tags</a></li>
                <li><a href="#">Category</a></li>
              </ul>
            </li>
            {% endif %}  <!-- g.identity.allow_write -->

            {% if g.identity.allow_edit %}
            <li class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">Comments <span class="caret"></span></a>
              <ul class="dropdown-menu" role="menu">
                <li><a href="{{ url_for('blog_admin.comments') }}">Pending</a></li>
                <li><a href="{{ url_for('blog_admin.comments_approved') }}">Approved</a></li>
              </ul>
            </li>
            {% endif %}

            {% if g.identity.allow_admin %}
            <li class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">Users <span class="caret"></span></a>
              <ul class="dropdown-menu" role="menu">
                <li><a href="{{ url_for('useraccounts.users') }}">All Users</a></li>
                <li><a href="{{ url_for('useraccounts.add_user') }}">New User</a></li>
              </ul>
            </li>
            {% endif %}

            {% if g.identity.allow_admin %}
            <li class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">Super Admin <span class="caret"></span></a>
              <ul class="dropdown-menu" role="menu">
                <li><a href="#">Super Posts</a></li>
                <li><a href="#">Users</a></li>
                <li class="divider"></li>
                <li><a href="{{ url_for('blog_admin.post_statistics') }}">Posts Statistics</a></li>
              </ul>
            </li>
            {% endif %}
          </ul>

        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
          <ul class="nav navbar-nav navbar-right">
          {% if current_user.is_authenticated %}
            <li class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">{{ current_user.username }} <span class="caret"></span></a>
              <ul class="dropdown-menu" role="menu">
                <li><a href="{{ url_for('useraccounts.setting') }}"><span class="glyphicon glyphicon-cog"></span>&nbsp; Settings</a></li>
                <li class="divider"></li>
                <li><a href="{{ url_for('useraccounts.logout') }}"><span class="glyphicon glyphicon-off"></span>&nbsp; Logout</a></li>
              </ul>
            </li>
          {% else %}
            <li><a href="{{ url_for('useraccounts.login') }}">Login</a></li>
            <li><a href="{{ url_for('useraccounts.register')}}">Regster</a></li>
          {% endif %}
          </ul>
        </div>
        </div>
      </div>
    </nav>


    <!-- Page Header -->
    <!-- Set your background image for this header on the line below. -->
    {%block header %}{% endblock %}
    <div class="container">
        {% import "_msg.html" as messages %}
        {{ messages.render_msg() }}
        <!-- Main Content -->
        {%block main %}{% endblock %}
    </div>
    <hr>

    <!-- Footer -->
    <footer>
        <div class="container">
            <div class="row">
                <div class="col-lg-8 col-lg-offset-2 col-md-10 col-md-offset-1">
                    <ul class="list-inline text-center">
                        <li>
                            <a href="https://creativecommons.org/licenses/" target="_blank">
                                <span class="fa-stack fa-lg">
                                    <i class="fa fa-circle fa-stack-2x"></i>
                                    <i class="fa fa-twitter fa-stack-1x fa-inverse"></i>
                                </span>
                            </a>
                        </li>
                        <li>
                            <a href="#">
                                <span class="fa-stack fa-lg">
                                    <i class="fa fa-circle fa-stack-2x"></i>
                                    <i class="fa fa-facebook fa-stack-1x fa-inverse"></i>
                                </span>
                            </a>
                        </li>
                        <li>
                            <a href="https://github.com/cylmemory/SimpleBlog" target="_blank">
                                <span class="fa-stack fa-lg">
                                    <i class="fa fa-circle fa-stack-2x"></i>
                                    <i class="fa fa-github fa-stack-1x fa-inverse"></i>
                                </span>
                            </a>
                        </li>
                    </ul>
                    <p class="copyright text-muted text-center">Copyright &copy; Simple Blog 2018</p>
                </div>
            </div>
        </div>
    </footer>
    <!-- jQuery -->
    <script src="//cdn.bootcss.com/jquery/2.1.4/jquery.min.js"></script>
    <!-- Bootstrap Core JavaScript -->
    <script src="//cdn.bootcss.com/bootstrap/3.3.5/js/bootstrap.min.js"></script>
    <script src="//cdn.bootcss.com/bootbox.js/4.4.0/bootbox.min.js"></script>

    <!-- Custom Theme JavaScript -->
    {% block js %}
    {% endblock %}

</body>
</html>